---
title: "MP2"
author: "Zoe Meers"
date: "3/20/2017"
output: html_document
---
```{r}
#load data sets
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
library(tidyverse)
library(maps)
library(maptools)
library(mapdata)
library(dplyr)
```


```{r}
#filter candidates by year
candidates2012<-filter(candidates, cand_election_yr=="2012")
#filter contributions by individual contributions to HELP a candidate be elected
contributions2012<-filter(contributions, transaction_type=="24E")
#filter negative contributions
contributions2012<-filter(contributions2012, transaction_amt==gsub('-[A-z ]*', '', transaction_amt))
contributions2012<-filter(contributions2012, transaction_amt==gsub('0', '', transaction_amt))

```
```{r}
#filter transactions for 2012 election only.
#2010 midterms were helf on the 11/02/10, so transactions on or after this date are most likely for 2012
contributions2012<- filter(contributions, transaction_dt>="11022010")
#filters for transaction dates before the 2012 election. We don't want contributions for the 2014 midterms.
contributions2012<- filter(contributions, transaction_dt<"11052012")
```

```{r}
sum_cand<- aggregate(transaction_amt~cand_id, data=contributions2012, FUN=function(x) c(sum=sum(x), count=length(x)))
sum_cand <- sum_cand[-c(1), ]
sum_cand$'transaction_amt' = round(sum_cand$'transaction_amt')
```


```{r}
party_id <- candidates2012 %>%
  inner_join(sum_cand, by = ("cand_id"))
```


```{r}
#democrats2012 - candidates
democrats2012<- filter(party_id, cand_party_affiliation=="DEM")
#repubs2012 - candidates
republicans2012 <- filter(party_id, cand_party_affiliation=="REP")
```


```{r}
#aggregate sum of transaction amt by state - dem
sum_dem<- aggregate(transaction_amt~cand_office_state, data=democrats2012, FUN=function(x) c(sum=sum(x), count=length(x)))
#aggregate sum of transaction amt by state - rep
sum_rep<- aggregate(transaction_amt~cand_office_state, data=republicans2012, FUN=function(x) c(sum=sum(x), count=length(x)))
```
```{r}
#rename variable to state
sum_dem <- rename(sum_dem, "State"=cand_office_state)
sum_rep <- rename(sum_rep, "State"=cand_office_state)
```
```{r}
#cut US, PR, AS, GU, DC, MP, VI
sum_dem <- sum_dem[-c(3,8,12,41,47,50), ]
sum_rep <- sum_rep[-c(11,45), ]
sum_dem$'V1' = round(sum_dem$'V1')
sum_rep$'V1' = round(sum_rep$'V1')
```

```{r}
#Change state abbreviations to name for sum_dem
sum_dem$State <- gsub("AL", "alabama", sum_dem$State)
sum_dem$State <- gsub("AK", "alaska", sum_dem$State)
sum_dem$State <- gsub("AR", "arkansas", sum_dem$State)
sum_dem$State <- gsub("AZ", "arizona", sum_dem$State)
sum_dem$State <- gsub("CA", "california", sum_dem$State)
sum_dem$State <- gsub("CO", "colorado", sum_dem$State)
sum_dem$State <- gsub("CT", "connecticut", sum_dem$State)
sum_dem$State <- gsub("DE", "delaware", sum_dem$State)
sum_dem$State <- gsub("FL", "florida", sum_dem$State)
sum_dem$State <- gsub("GA", "georgia", sum_dem$State)
sum_dem$State <- gsub("HI", "hawaii", sum_dem$State)
sum_dem$State <- gsub("IA", "iowa", sum_dem$State)
sum_dem$State <- gsub("ID", "idaho", sum_dem$State)
sum_dem$State <- gsub("IL", "illinois", sum_dem$State)
sum_dem$State <- gsub("IN", "indiana", sum_dem$State)
sum_dem$State <- gsub("KS", "kansas", sum_dem$State)
sum_dem$State <- gsub("KY", "kentucky", sum_dem$State)
sum_dem$State <- gsub("LA", "louisiana", sum_dem$State)
sum_dem$State <- gsub("MA", "massachusetts", sum_dem$State)
sum_dem$State <- gsub("MD", "maryland", sum_dem$State)
sum_dem$State <- gsub("ME", "maine", sum_dem$State)
sum_dem$State <- gsub("MI", "michigan", sum_dem$State)
sum_dem$State <- gsub("MN", "minnesota", sum_dem$State)
sum_dem$State <- gsub("MO", "missouri", sum_dem$State)
sum_dem$State <- gsub("MS", "mississippi", sum_dem$State)
sum_dem$State <- gsub("MT", "montana", sum_dem$State)
sum_dem$State <- gsub("NC", "north carolina", sum_dem$State)
sum_dem$State <- gsub("ND", "north dakota", sum_dem$State)
sum_dem$State <- gsub("NE", "nebraska", sum_dem$State)
sum_dem$State <- gsub("NH", "new hampshire", sum_dem$State)
sum_dem$State <- gsub("NJ", "new jersey", sum_dem$State)
sum_dem$State <- gsub("NM", "new mexico", sum_dem$State)
sum_dem$State <- gsub("NV", "nevada", sum_dem$State)
sum_dem$State <- gsub("NY", "new york", sum_dem$State)
sum_dem$State <- gsub("OH", "ohio", sum_dem$State)
sum_dem$State <- gsub("OK", "oklahoma", sum_dem$State)
sum_dem$State <- gsub("OR", "oregon", sum_dem$State)
sum_dem$State <- gsub("PA", "pennsylvania", sum_dem$State)
sum_dem$State <- gsub("RI", "rhode island", sum_dem$State)
sum_dem$State <- gsub("SC", "south carolina", sum_dem$State)
sum_dem$State <- gsub("SD", "south dakota", sum_dem$State)
sum_dem$State <- gsub("TN", "tennessee", sum_dem$State)
sum_dem$State <- gsub("TX", "texas", sum_dem$State)
sum_dem$State <- gsub("UT", "utah", sum_dem$State)
sum_dem$State <- gsub("VA", "virginia", sum_dem$State)
sum_dem$State <- gsub("VT", "vermont", sum_dem$State)
sum_dem$State <- gsub("WA", "washington", sum_dem$State)
sum_dem$State <- gsub("WV", "west virginia", sum_dem$State)
sum_dem$State <- gsub("WI", "wisconsin", sum_dem$State)
sum_dem$State <- gsub("WY", "wyoming", sum_dem$State)



```

```{r}
#change state abbreviations to names for sum_rep
sum_rep$State <- gsub("AL", "alabama", sum_rep$State)
sum_rep$State <- gsub("AK", "alaska", sum_rep$State)
sum_rep$State <- gsub("AR", "arkansas", sum_rep$State)
sum_rep$State <- gsub("AZ", "arizona", sum_rep$State)
sum_rep$State <- gsub("CA", "california", sum_rep$State)
sum_rep$State <- gsub("CO", "colorado", sum_rep$State)
sum_rep$State <- gsub("CT", "connecticut", sum_rep$State)
sum_rep$State <- gsub("DE", "delaware", sum_rep$State)
sum_rep$State <- gsub("FL", "florida", sum_rep$State)
sum_rep$State <- gsub("GA", "georgia", sum_rep$State)
sum_rep$State <- gsub("HI", "hawaii", sum_rep$State)
sum_rep$State <- gsub("IA", "iowa", sum_rep$State)
sum_rep$State <- gsub("ID", "idaho", sum_rep$State)
sum_rep$State <- gsub("IL", "illinois", sum_rep$State)
sum_rep$State <- gsub("IN", "indiana", sum_rep$State)
sum_rep$State <- gsub("KS", "kansas", sum_rep$State)
sum_rep$State <- gsub("KY", "kentucky", sum_rep$State)
sum_rep$State <- gsub("LA", "louisiana", sum_rep$State)
sum_rep$State <- gsub("MA", "massachusetts", sum_rep$State)
sum_rep$State <- gsub("MD", "maryland", sum_rep$State)
sum_rep$State <- gsub("ME", "maine", sum_rep$State)
sum_rep$State <- gsub("MI", "michigan", sum_rep$State)
sum_rep$State <- gsub("MN", "minnesota", sum_rep$State)
sum_rep$State <- gsub("MO", "missouri", sum_rep$State)
sum_rep$State <- gsub("MS", "mississippi", sum_rep$State)
sum_rep$State <- gsub("MT", "montana", sum_rep$State)
sum_rep$State <- gsub("NC", "north carolina", sum_rep$State)
sum_rep$State <- gsub("ND", "north dakota", sum_rep$State)
sum_rep$State <- gsub("NE", "nebraska", sum_rep$State)
sum_rep$State <- gsub("NH", "new hampshire", sum_rep$State)
sum_rep$State <- gsub("NJ", "new jersey", sum_rep$State)
sum_rep$State <- gsub("NM", "new mexico", sum_rep$State)
sum_rep$State <- gsub("NV", "nevada", sum_rep$State)
sum_rep$State <- gsub("NY", "new york", sum_rep$State)
sum_rep$State <- gsub("OH", "ohio", sum_rep$State)
sum_rep$State <- gsub("OK", "oklahoma", sum_rep$State)
sum_rep$State <- gsub("OR", "oregon", sum_rep$State)
sum_rep$State <- gsub("PA", "pennsylvania", sum_rep$State)
sum_rep$State <- gsub("RI", "rhode island", sum_rep$State)
sum_rep$State <- gsub("SC", "south carolina", sum_rep$State)
sum_rep$State <- gsub("SD", "south dakota", sum_rep$State)
sum_rep$State <- gsub("TN", "tennessee", sum_rep$State)
sum_rep$State <- gsub("TX", "texas", sum_rep$State)
sum_rep$State <- gsub("UT", "utah", sum_rep$State)
sum_rep$State <- gsub("VA", "virginia", sum_rep$State)
sum_rep$State <- gsub("VT", "vermont", sum_rep$State)
sum_rep$State <- gsub("WA", "washington", sum_rep$State)
sum_rep$State <- gsub("WV", "west virginia", sum_rep$State)
sum_rep$State <- gsub("WI", "wisconsin", sum_rep$State)
sum_rep$State <- gsub("WY", "wyoming", sum_rep$State)

```
```{r}
sapply(sum_dem, class)
```

```{r}
all_states <- map_data("state")
all_states <- rename(all_states, "State"=region)
class(sum_dem$V1) <- "numeric"
as.data.frame(sum_dem)
class(sum_dem$State)
class(sum_dem$V1)
sum_dem <- mutate(sum_dem, as.data.frame(V1))
class(all_states$State)
#join states together using left join
MyMap_dem <- left_join(all_states, sum_dem, by ="State")
MyMap_rep <- left_join(all_states, sum_rep, by="State")
```




```{r}
#theme_nothing() didn't work when I called it so I found the function and c/p it.
theme_nothing <- function(base_size = 12, base_family = "Helvetica")
  {
  theme_bw(base_size = base_size, base_family = base_family) %+replace%
      theme(
            rect             = element_blank(),
            line             = element_blank(),
            text             = element_blank(),
            axis.ticks.margin = unit(0, "lines")
           )
  }

```
```{r}
#MAPS
states_map <- ggplot(data = all_states, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  geom_polygon(color = "black", fill = "gray")
states_map + theme_nothing()
ditch_the_axes <- theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank()
  )
#Republican map
Rep_Map <- states_map + 
      geom_polygon(data = MyMap_rep, aes(fill = V1), color = "white") +
      geom_polygon(color = "black", fill = NA) +
      theme_bw() +
      ditch_the_axes
Rep_Map
#Democrats map 
Dem_Map <- states_map + 
      geom_polygon(data = MyMap_dem, aes(fill = V1), color = "white") +
      geom_polygon(color = "black", fill = NA) +
      theme_bw() +
      ditch_the_axes
Dem_Map

```


