---
title: "MP2"
author: "Zoe Meers"
date: "3/20/2017"
output: html_document
---
```{r}
#load data sets
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
library(tidyverse)
#install
library(choroplethrMaps)
#install
library(choroplethr)
#install
library(maps)
#install
library(fiftystater)
#install
library(maptools)
#install
library(rgeos)
#install
library(rgdal)
library(dplyr)
```


```{r}
#filter candidates by year
candidates2012<-filter(candidates, cand_election_yr=="2012")
```
```{r}
#filter transactions for 2012 election only.
#2010 midterms were helf on the 11/02/10, so transactions on or after this date are most likely for 2012
contributions2012<- filter(contributions, transaction_dt>="11022010")
#filters for transaction dates before the 2012 election. We don't want contributions for the 2014 midterms.
contributions2012<- filter(contributions, transaction_dt<"11052012")
```
```{r}
#Based on our assumptions, the transaction amount should always be a + number. The data does not look clean (many transaction amounts are - amounts)
#We decided to take away the negative sign using regex (gsub) and assume that was the amount the person contributed
contributions2012$transaction_amt= as.numeric(gsub("-", "", contributions2012$transaction_amt))
```
```{r}
mean_cand<- aggregate(transaction_amt~cand_id, data=contributions2012, FUN=function(x) c(mean=mean(x), count=length(x)))
mean_cand <- mean_cand[-c(1), ]
mean_cand$'transaction_amt' = round(mean_cand$'transaction_amt')
```


```{r}
party_id <- candidates2012 %>%
  inner_join(mean_cand, by = ("cand_id"))
```


```{r}
#democrats2012 - candidates
democrats2012<- filter(party_id, cand_party_affiliation=="DEM")
#repubs2012 - candidates
republicans2012 <- filter(party_id, cand_party_affiliation=="REP")
```

```{r}
#aggregate mean of transaction amt by state - dem
mean_dem<- aggregate(transaction_amt~cand_office_state, data=democrats2012, FUN=function(x) c(mean=mean(x), count=length(x)))
#aggregate mean of transaction amt by state - rep
mean_rep<- aggregate(transaction_amt~cand_office_state, data=republicans2012, FUN=function(x) c(mean=mean(x), count=length(x)))
```

```{r}
#cut US, PR, AS, GU, DC, MP, VI
mean_dem <- mean_dem[-c(3,8,12,41,47,50), ]
mean_rep <- mean_rep[-c(11,45), ]
mean_dem$'V1' = round(mean_dem$'V1')
mean_rep$'V1' = round(mean_rep$'V1')
```

```{r}
#MAP
#using code from: https://cran.r-project.org/web/packages/fiftystater/vignettes/fiftystater.html
transform_state <- function(object, rot, scale, shift){
  object %>% elide(rotate = rot) %>%
    elide(scale = max(apply(bbox(object), 1, diff)) / scale) %>%
    elide(shift = shift)
}

#state shape file from
# http://www.arcgis.com/home/item.html?id=f7f805eb65eb4ab787a0a3e1116ca7e5
loc <- file.path(tempdir(), "stats_dat")
unzip(system.file("extdata", "states_21basic.zip", package = "fiftystater"),
      exdir = loc)
fifty_states_sp <- readOGR(dsn = loc, layer = "states", verbose = FALSE) %>%
  spTransform(CRS("+init=epsg:2163"))

alaska <- fifty_states_sp[fifty_states_sp$STATE_NAME == "Alaska", ] %>%
  transform_state(-35, 2.5, c(-2400000, -2100000))
proj4string(alaska) <- proj4string(fifty_states_sp)

hawaii <- fifty_states_sp[fifty_states_sp$STATE_NAME == "Hawaii", ] %>%
  transform_state(-35, .75, c(-1170000,-2363000))
proj4string(hawaii) <- proj4string(fifty_states_sp)

fifty_states <-
  fifty_states_sp[!fifty_states_sp$STATE_NAME %in% c("Alaska","Hawaii"), ] %>%
  rbind(alaska) %>%
  rbind(hawaii) %>%
  spTransform(CRS("+init=epsg:4326")) %>%
  fortify(region = "STATE_NAME") %>%
  mutate(id = tolower(id))
```

```{r}
#democrats map
data("fifty_states") # this line is optional due to lazy data loading
ggplot(mean_dem, aes(map_id = "cand_office_state")) + 
  # map points to the fifty_states shape data
  geom_map(aes(fill = V1), map = fifty_states) + 
  expand_limits(x = fifty_states$long, y = fifty_states$lat) +
  coord_map() +
  scale_x_continuous(breaks = NULL) + 
  scale_y_continuous(breaks = NULL) +
  labs(x = "", y = "") +
  theme(legend.position = "bottom", 
        panel.background = element_blank())
```



```{r}
#republicans map
data("fifty_states") # this line is optional due to lazy data loading
ggplot(mean_rep, aes(map_id = "cand_office_state")) + 
  # map points to the fifty_states shape data
  geom_map(aes(fill = V1), map = fifty_states) + 
  expand_limits(x = fifty_states$long, y = fifty_states$lat) +
  coord_map() +
  scale_x_continuous(breaks = NULL) + 
  scale_y_continuous(breaks = NULL) +
  labs(x = "", y = "") +
  theme(legend.position = "bottom", 
        panel.background = element_blank())
```


