---
title: "MP2"
author: "Zoe Meers"
date: "3/20/2017"
output: html_document
---
```{r}
#load data sets
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
library(tidyverse)
#install
library(choroplethrMaps)
#install
library(choroplethr)
#install
library(maps)
#install
library(fiftystater)
```
```{r}
str(house_elections)
str(committees)
str(candidates)
str(contributions)
```



```{r}
#filter candidates by year
candidates2012<-filter(candidates, cand_election_yr=="2012")
```
```{r}
#filter transactions for 2012 election only.
#2010 midterms were helf on the 11/02/10, so transactions on or after this date are most likely for 2012
contributions2012<- filter(contributions, transaction_dt>="11022010")
#filters for transaction dates before the 2012 election. We don't want contributions for the 2014 midterms.
contributions2012<- filter(contributions, transaction_dt<"11052012")
```
```{r}
#Based on our assumptions, the transaction amount should always be a + number. The data does not look clean (many transaction amounts are - amounts)
#We decided to take away the negative sign using regex (gsub) and assume that was the amount the person contributed
contributions2012$transaction_amt= as.numeric(gsub("-", "", contributions2012$transaction_amt))
#move transaction amount to candidates2012
#candidates2012 <- cbind(candidates2012, contributions2012$transaction_amt)
#summarize cont2012 by cand_id
#summarize(contributions2012, n_distinct("cand_id"))
```
```{r}
mean_cand<- aggregate(transaction_amt~cand_id, data=contributions2012, FUN=function(x) c(mean=mean(x), count=length(x)))
mean_cand <- mean_cand[-c(1), ]
mean_cand$'transaction_amt' = round(mean_cand$'transaction_amt')
```


```{r}
party_id <- candidates2012 %>%
  inner_join(mean_cand, by = ("cand_id"))

```


```{r}
#democrats2012 - candidates
democrats2012<- filter(party_id, cand_party_affiliation=="DEM")
#repubs2012 - candidates
republicans2012 <- filter(party_id, cand_party_affiliation=="REP")
```

```{r}
#aggregate mean of transaction amt by state - dem
mean_dem<- aggregate(transaction_amt~cand_office_state, data=democrats2012, FUN=function(x) c(mean=mean(x), count=length(x)))
#aggregate mean of transaction amt by state - rep
mean_rep<- aggregate(transaction_amt~cand_office_state, data=republicans2012, FUN=function(x) c(mean=mean(x), count=length(x)))
```

```{r}
#cut US, PR, AS, GU, DC, MP, VI
mean_dem <- mean_dem[-c(3,8,12,41,47,50), ]
mean_rep <- mean_rep[-c(11,45), ]
mean_dem$'V1' = round(mean_dem$'V1')
mean_rep$'V1' = round(mean_rep$'V1')
```

```{r}
#democrats map
data("fifty_states") # this line is optional due to lazy data loading
ggplot(mean_dem, aes(map_id = "cand_office_state")) + 
  # map points to the fifty_states shape data
  geom_map(aes(fill = V1), map = fifty_states) + 
  expand_limits(x = fifty_states$long, y = fifty_states$lat) +
  coord_map() +
  scale_x_continuous(breaks = NULL) + 
  scale_y_continuous(breaks = NULL) +
  labs(x = "", y = "") +
  theme(legend.position = "bottom", 
        panel.background = element_blank())
```



```{r}
#republicans map
data("fifty_states") # this line is optional due to lazy data loading
ggplot(mean_rep, aes(map_id = "cand_office_state")) + 
  # map points to the fifty_states shape data
  geom_map(aes(fill = V1), map = fifty_states) + 
  expand_limits(x = fifty_states$long, y = fifty_states$lat) +
  coord_map() +
  scale_x_continuous(breaks = NULL) + 
  scale_y_continuous(breaks = NULL) +
  labs(x = "", y = "") +
  theme(legend.position = "bottom", 
        panel.background = element_blank())
```
```

